TrajectoryPlannerROS:
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 2.4
  max_vel_x: 0.45
  min_vel_x: 0.02
  max_vel_theta: 0.9
  min_vel_theta: 0.03
  min_in_place_vel_theta: 0.03
  escape_vel: -0.2
  holonomic_robot: false

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.15

  meter_scoring: true
  global_frame_id: map

