DWAPlannerROS:
  meter_scoring: true
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 1.0
  max_trans_vel: 0.5
  min_trans_vel: 0.10
  max_vel_x: 0.5
  min_vel_x: -0.5
  max_vel_y: 0.0
  min_vel_y: -0.0
  max_rot_vel: 0.86
  min_rot_vel: 0.2

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.15
  sim_time: 1.7
  vx_samples: 10
  vy_samples: 10
  vtheta_samples: 30
  path_distance_bias: 16.0
  goal_distance_bias: 24.0
  occdist_scale: 1.0
  stop_time_buffer: 0.2
  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.2
