global_frame: map
robot_frame: base_footprint
robot_base_frame: base_link
mesh_part: mesh
layers:
  - name: 'height_diff'
    type: 'mesh_layers/HeightDiffLayer'
  - name: 'roughness'
    type: 'mesh_layers/RoughnessLayer'
  - name: 'inflation'
    type: 'mesh_layers/InflationLayer'

height_diff:
  factor: 0.3

roughness:
  factor: 0.3

infalation:
  factor: 1.0
