planners:
  - name: 'mesh_planner'
    type: 'mesh_planner/MeshPlanner'

controllers:
  - name: 'mesh_controller'
    type: 'mesh_controller/MeshController'

mesh_planner:
  cost_limit: 6.8

mesh_controller:
  ang_vel_factor: 7.0
  lin_vel_factor: 1.0

planner_patience: 10.0
planner_max_retries: 2

controller_patience: 5.0
controller_max_retries: 2

robot_frame: 'base_footprint'
dist_tolerance: 0.2
angle_tolerance: 0.8
